name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: S3 Backup
      uses: peter-evans/s3-backup@v1.0.0
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        MIRROR_TARGET: ${{ secrets.AWS_S3_BUCKET }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      with:
        args: --overwrite --remove